config/routes.rb
Rails.application.routes.draw do
  resources :cities, only: [:create, :index, :show, :new, :edit]
end

app/models/city.rb
class City < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities - показать все города
  def index
    @cities = City.all
  end

  # GET /cities/new - html форма для создания нового города
  def new
    @city = City.new
  end

  # POST /cities - добавление нового города в базу
  def create
    @city = City.new(city_params)

    if @city.save
      redirect_to @city, notice: 'City was successfully created.'
    else
      render :new
    end
  end

  private
    # находит город по id
    def set_city
      @city = City.find(params[:id])
    end

    # параметры, разрешенные для создания новой записи в базе данных
    def city_params
      params.require(:city).permit(:name, :latitude, :longitude, :population, :economy, :image)
    end
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :population %><br>
    <%= f.number_field :population %>
  </div>
  <div class="field">
    <%= f.label :economy %><br>
    <%= f.text_field :economy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/index.html.erb
<h1>Города</h1>

<ul>
  <% @cities.each do |city| %>
    <li>
      <h3>
        <%= link_to city.name, city %>
      </h3>
    </li>
  <% end -%>
</ul>
<%= link_to 'Добавить город', new_city_path %>

app/views/cities/new.html.erb
<h1>Добавить город</h1>  

<%= form_for :city, url: cities_path do |f| %>

  <% if not @city.nil? and @city.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@city.errors.count, "error") %> prohibited
      this city from being saved:</h2>
    <ul>
    <% @city.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label  "Название"%><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label "Широта" %><br>
    <%= f.text_field :latitude %>
  </p>

  <p>
    <%= f.label "Долгота" %><br>
    <%= f.text_field :longitude %>
  </p>

  <p>
    <%= f.label "Население" %><br>
    <%= f.text_field :population %>
  </p>

  <p>
    <%= f.label "Экономика" %><br>
    <%= f.text_area :economy %>
  </p>

  <p>
    <%= f.label "Изображение" %><br />
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit 'Создать' %>
  </p>

  <% end %>

  

<%= link_to '<- Назад', cities_path %>

app/views/cities/show.html.erb
<p>
  <strong>Город:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Население:</strong>
  <%= @city.population %>
</p>

<p>
  <strong>Широта:</strong>
  <%= @city.latitude %>
</p>

<p>
  <strong>Долгота:</strong>
  <%= @city.longitude %>
</p>

<p>
  <strong>Экономика:</strong>
  <%= @city.economy %>
</p>

<p>
  <strong>Фото:</strong>
  <%= image_tag @city.image.url(:medium) %>
</p>

<%= link_to '<- Назад', cities_path %>

<%= link_to 'Посмотреть на карте ->', "https://www.google.ru/maps/@#{@city.latitude},#{@city.longitude},11z" ,target: "_blank" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewGis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>